# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: Solution Template PR
on:
  workflow_dispatch:
  pull_request:
    branches: [ $default-branch ]
jobs:
  ValidateARMTemplates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate ARM template from Bicep templates
        uses: Azure/bicep-build-action@v1.0.1
        with:
          bicepFilePath: ./marketplace/application/base-image-vm/app-contents/mainTemplate.bicep
          outputFilePath: ./marketplace/application/base-image-vm/app-contents/mainTemplate.json
      - name: Run ARM-TTK
        uses: ./.github/actions/run-armttk
        with:
          templatesFolderPath: ./marketplace/application/base-image-vm/app-contents
          armttkVersion: aka.ms/arm-ttk-latest
  VerifyOfferCreation:
    runs-on: ubuntu-latest
    needs: ValidateARMTemplates
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and create/update offer
        uses: ./.github/actions/commercial-marketplace
        with:
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          offerType: st
          command: create
          applicationName: contoso-st
          planName: base-image-vm
          applicationDirectory: ./marketplace/application/base-image-vm
      - name: Delete offer
        uses: ./.github/actions/commercial-marketplace
        with:
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          offerType: st
          command: delete
          applicationName: contoso-st
        timeout-minutes: 5
