# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: Solution Template PR

on:
  workflow_dispatch:
  pull_request:
    branches: [ $default-branch ]

env:
  APPLICATION_DIRECTORY: marketplace/application/base-image-vm
  TEST_DIRECTORY: marketplace/application/tests

jobs:
  ValidateARMTemplates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate ARM template from Bicep templates
        uses: Azure/bicep-build-action@v1.0.1
        with:
          bicepFilePath: "${{ env.APPLICATION_DIRECTORY }}/app-contents/mainTemplate.bicep"
          outputFilePath: "${{ env.APPLICATION_DIRECTORY }}/app-contents/mainTemplate.json"
      - name: Run ARM-TTK
        uses: ./.github/actions/run-armttk
        with:
          templatesFolderPath: "${{ env.APPLICATION_DIRECTORY }}/app-contents"
          armttkVersion: aka.ms/arm-ttk-latest
  RunTests:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Pester tests
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck
          Set-Location ${{ env.APPLICATION_DIRECTORY }}
          Invoke-Pester -Path "../tests"
        shell: pwsh
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Run Deployment tests
        run: |
          Set-Location ${{ env.TEST_DIRECTORY }}
          ./validateDeployment.ps1 "../../../${{ env.APPLICATION_DIRECTORY }}"
        shell: pwsh
  VerifyOfferCreation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and create/update offer
        uses: ./.github/actions/commercial-marketplace
        with:
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          offerType: st
          command: create
          applicationName: contoso-app
          planName: base-image-vm
          applicationDirectory: ${{ env.APPLICATION_DIRECTORY }}
        timeout-minutes: 5
      - name: Delete offer
        uses: ./.github/actions/commercial-marketplace
        with:
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          offerType: app
          command: delete
          applicationName: contoso-app
        timeout-minutes: 5
