name: CreateManagedAppOffer

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AAD_CLIENTID}}
          tenant-id: ${{ secrets.AAD_TENANTID}}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID}}

      - name: Azure CLI Action
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az account show
