# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: Virtual Machine PR
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
jobs:
  ValidatePackerTemplate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: build.BasicWindowsVMImage.pkr.hcl source.windowsvhd.pkr.hcl
          working_directory: marketplace/virtual-machine/basic-windows-vm
  BuildValidateImage:
    runs-on: ubuntu-latest
    needs: ValidatePackerTemplate
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Packer Variables
        uses: microsoft/variable-substitution@v1
        with:
          files: marketplace/virtual-machine/basic-windows-vm/variables.pkr.json
        env:
          variable.artifact_storage_account.default: azmpstor
          variable.image_vhd_name.default: basicwinvm_${{ github.run_number }}
          variable.region.default: australiaeast
          variable.resource_group_name.default: azmp-rg
          variable.temp_resource_group_name.default: basicwinvm-${{ github.run_number }}-rg
      - name: Build Image
        id: build-image
        uses: ./.github/actions/packer-build
        with:
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          target: .
          workingDirectory: marketplace/virtual-machine/basic-windows-vm
      - name: Check VHD URI
        shell: bash
        run: |
          echo "${{ steps.build-image.outputs.vhdUri }}"
      - name: Validate Image
        id: validate-image
        uses: ./.github/actions/validate-image
        with:
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          vhdUri: ${{ steps.build-image.outputs.vhdUri }}
          location: australiaeast
      - name: Build and create/update offer
        uses: ./.github/actions/commercial-marketplace
        with:
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          offerType: vm
          command: create
          applicationName: contoso-vm
          applicationDirectory: ./marketplace/virtual-machine/basic-windows-vm
          logosPath: ./marketplace/virtual-machine/basic-windows-vm/logos
          storageConnectionString: ${{ secrets.AZURE_STORAGECONNECTIONSTRING }}
        timeout-minutes: 5
      - name: Delete offer
        uses: ./.github/actions/commercial-marketplace
        with:
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          offerType: vm
          command: delete
          applicationName: contoso-vm
        timeout-minutes: 5
